export default [
    {
        id: 'start',
        name: '5G Start',
        details: [
            '5G Access',
            '5G Nationwide',
            'Apple Arcade for 6 months on us',
            'Google Play Pass for 6 months on us',
            'Apple Music for 6 months on us',
        ],
    },
    {
        id: 'play_more',
        name: '5G Play More (Premium Plan)',
        details: [
            '5G Total Access',
            '5G Ultra Wideband',
            '5G Nationwide',
            '50 GB Premium Network Access',
            '25 GB premium mobile hotspot data, then unlimited lower-speed data',
            'Hulu, Disney+ and ESPN+ included',
            'Apple Arcade or Google Play Pass',
            'Apple Music for 6 months on us',
        ],
    },
    {
        id: 'do_more',
        name: '5G Do More (Premium Plan)',
        details: [
            '5G Total Access',
            '5G Ultra Wideband',
            '5G Nationwide',
            '50 GB Premium Network Access',
            '25 GB premium mobile hotspot data, then unlimited lower-speed data',
            '600 GB of Verizon Cloud Storage',
            '1 TravelPass day per month',
            'Up to 50% off select connected device plans ($5 Smart Watch / $10 Tablets)',
            'Apple Music, Disney+, Apple Arcade, and Google Play Pass for 6 months on us',
        ],
    },
    {
        id: 'get_more',
        name: '5G Get More (Premium Plan)',
        details: [
            '5G Total Access',
            '5G Ultra Wideband',
            '5G Nationwide',
            'Unlimited Premium Network Access',
            '50 GB premium mobile hotspot data, then unlimited lower-speed data',
            'Hulu, Disney+ and ESPN+ included',
            'Apple Arcade or Google Play Pass for 12 months on us',
            'Apple Music included',
            '1 TravelPass day per month',
            '600 GB of Verizon Cloud Storage',
            'Up to 50% off select connected device plans ($5 Smart Watch / $10 Tablets)',
        ],
    },
];
